"use client";

import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ProductCarousel } from "@/components/features/products/product-carousel";
import { ComparisonTable } from "@/components/features/products/comparison-table";
import { sendChatMessage, compareProducts, type ChatMessage } from "@/lib/api/chat";
import type { Product } from "@/types/product";
import { Send, Loader2, Sparkles, X, MessageCircle, Maximize2, Scale } from "lucide-react";
import { toast } from "sonner";
import { ROUTES } from "@/lib/constants";

const SUGGESTIONS = [
  "Show me gym wear that works for meetings",
  "I need something for a formal event",
  "What are your best sellers?",
  "Show me casual everyday wear",
];

const STORAGE_KEY = "neusearch_chat_messages";

const getDefaultMessage = (): ChatMessage => ({
  role: "assistant",
  content: "Hello! I'm your product recommendation assistant. How can I help you find the perfect products today?",
  timestamp: new Date().toISOString(),
});

// Note: Follow-ups are now AI-generated by the backend based on user's previous message

// Load messages from localStorage
const loadMessagesFromStorage = (): ChatMessage[] => {
  if (typeof window === "undefined") return [];
  
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch (error) {
    console.error("Error loading messages from localStorage:", error);
  }
  return [getDefaultMessage()];
};

// Save messages to localStorage
const saveMessagesToStorage = (messages: ChatMessage[]) => {
  if (typeof window === "undefined") return;
  
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages));
  } catch (error) {
    console.error("Error saving messages to localStorage:", error);
  }
};

export function FloatingChatWidget() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isMounted, setIsMounted] = useState(false);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Load messages from localStorage only on client side after mount
  useEffect(() => {
    setIsMounted(true);
    const loadedMessages = loadMessagesFromStorage();
    if (loadedMessages.length === 0) {
      setMessages([getDefaultMessage()]);
    } else {
      setMessages(loadedMessages);
    }
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  // Save messages to localStorage whenever they change
  useEffect(() => {
    if (isMounted) {
      saveMessagesToStorage(messages);
    }
  }, [messages, isMounted]);

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
      // Focus input when opened
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [messages, isOpen]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: ChatMessage = {
      role: "user",
      content: input.trim(),
      timestamp: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    const userInput = input.trim();
    setInput("");
    setIsLoading(true);

    try {
      // Check if this is a comparison request
      const isComparisonRequest = /compare|comparison|differences?|similarities?|vs|versus/i.test(userInput);
      
      // Get products from the last assistant message if it's a comparison request
      const lastAssistantMessage = [...messages].reverse().find(msg => msg.role === "assistant" && msg.products && msg.products.length >= 2);
      
      if (isComparisonRequest && lastAssistantMessage && lastAssistantMessage.products && lastAssistantMessage.products.length >= 2) {
        // Use products from the last message for comparison
        const productIds = lastAssistantMessage.products.slice(0, 4).map(p => p.id);
        
        const compareResponse = await compareProducts(productIds);
        
        const assistantMessage: ChatMessage = {
          role: "assistant",
          content: `Here's a detailed comparison of the ${compareResponse.products.length} products:`,
          timestamp: new Date().toISOString(),
          products: compareResponse.products,
          aiInsight: compareResponse.insight,
          suggestedFollowUps: [
            "Tell me more about the first product",
            "What are the best alternatives?",
            "Show me more options in this category",
          ],
        };

        setMessages((prev) => [...prev, assistantMessage]);
      } else {
        // Regular chat flow
      const conversationHistory = messages
        .filter((msg) => msg.role !== "assistant" || !msg.products)
        .map((msg) => ({
          role: msg.role,
          content: msg.content,
        }));

      const response = await sendChatMessage({
          message: userInput,
        conversation_history: conversationHistory,
        max_results: 5,
        similarity_threshold: 0.6,
      });

      const assistantMessage: ChatMessage = {
        role: "assistant",
        content: response.response,
        timestamp: new Date().toISOString(),
        products: response.products.length > 0 ? response.products : undefined,
          suggestedFollowUps: response.suggested_follow_ups && response.suggested_follow_ups.length > 0 
            ? response.suggested_follow_ups 
            : undefined,
      };

      setMessages((prev) => [...prev, assistantMessage]);
      }
    } catch (error) {
      console.error("Error sending message:", error);
      
      if (error instanceof Error) {
        if (error.message.includes("429")) {
          toast.error("Rate limit exceeded", {
            description: "Please wait a moment before sending another message.",
          });
        } else if (error.message.includes("NetworkError") || error.message.includes("Failed to fetch")) {
          toast.error("Network error", {
            description: "Please check your internet connection and try again.",
          });
        } else {
          toast.error("Failed to send message", {
            description: error.message || "Please try again later.",
          });
        }
      } else {
        toast.error("An unexpected error occurred", {
          description: "Please try again later.",
        });
      }
      
      const errorMessage: ChatMessage = {
        role: "assistant",
        content: "I'm sorry, I encountered an error. Please try again.",
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
      inputRef.current?.focus();
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInput(suggestion);
    inputRef.current?.focus();
  };

  const handleCompareClick = async (productIds: string[]) => {
    if (productIds.length < 2 || isLoading) return;
    
    setIsLoading(true);
    const userMessage: ChatMessage = {
      role: "user",
      content: `Compare these ${productIds.length} products`,
      timestamp: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMessage]);

    try {
      const compareResponse = await compareProducts(productIds);
      
      const assistantMessage: ChatMessage = {
        role: "assistant",
        content: `Here's a detailed comparison of the ${compareResponse.products.length} products:`,
        timestamp: new Date().toISOString(),
        products: compareResponse.products,
        aiInsight: compareResponse.insight,
        suggestedFollowUps: [
          "Tell me more about the first product",
          "What are the best alternatives?",
          "Show me more options in this category",
        ],
      };

      setMessages((prev) => [...prev, assistantMessage]);
    } catch (error) {
      console.error("Error comparing products:", error);
      toast.error("Failed to compare products", {
        description: "Please try again later.",
      });
      
      const errorMessage: ChatMessage = {
        role: "assistant",
        content: "I'm sorry, I couldn't compare the products. Please try again.",
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
      inputRef.current?.focus();
    }
  };

  return (
    <>
      {/* Floating Chat Button */}
      {!isOpen && (
        <button
          onClick={() => setIsOpen(true)}
          className="fixed bottom-4 right-4 sm:bottom-6 sm:right-6 z-50 h-12 w-12 sm:h-14 sm:w-14 rounded-full bg-primary text-primary-foreground shadow-lg hover:shadow-xl transition-all hover:scale-110 active:scale-95 flex items-center justify-center group touch-manipulation"
          aria-label="Open chat assistant"
        >
          <MessageCircle className="h-5 w-5 sm:h-6 sm:w-6" />
          <span className="absolute -top-1 -right-1 h-2.5 w-2.5 sm:h-3 sm:w-3 bg-red-500 rounded-full animate-pulse" />
        </button>
      )}

      {/* Chat Widget Overlay */}
      {isOpen && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 bg-black/50 z-40"
            onClick={() => setIsOpen(false)}
            aria-hidden="true"
          />
          
          {/* Chat Widget */}
          <div className="fixed inset-0 sm:inset-auto sm:bottom-6 sm:right-6 z-50 w-full sm:w-[420px] h-full sm:h-[600px] flex flex-col shadow-2xl rounded-none sm:rounded-lg overflow-hidden bg-background border-0 sm:border border-border">
            {/* Header */}
            <div className="border-b border-border/50 px-4 py-3 flex items-center justify-between shrink-0 bg-background">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                <h3 className="font-semibold">AI Assistant</h3>
              </div>
              <div className="flex items-center gap-2">
                <Link
                  href={ROUTES.CHAT}
                  onClick={() => setIsOpen(false)}
                  className="group flex items-center gap-1.5 px-2.5 py-1.5 rounded-md hover:bg-muted transition-all duration-300"
                  aria-label="Open full chat page"
                >
                  <Maximize2 className="h-3.5 w-3.5 group-hover:scale-110 transition-transform duration-300" />
                  <span className="text-xs font-medium hidden sm:inline">
                    Expand
                  </span>
                </Link>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => setIsOpen(false)}
                  className="h-8 w-8 hover:bg-muted"
                  aria-label="Close chat"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            </div>

            {/* Messages Area */}
            <div className="flex-1 overflow-y-auto px-4 pt-4 pb-4 bg-background min-h-0">
              {messages.map((message, index) => (
                <div key={index} className="mb-5 last:mb-0">
                  <div
                    className={`flex items-start gap-2.5 ${
                      message.role === "user" ? "justify-end" : "justify-start"
                    }`}
                  >
                    {message.role === "assistant" && (
                      <div className="shrink-0 w-7 h-7 rounded-full bg-primary flex items-center justify-center mt-0.5">
                        <Sparkles className="h-3.5 w-3.5 text-primary-foreground" />
                      </div>
                    )}
                    <div
                      className={`flex-1 max-w-[85%] ${
                        message.role === "user"
                          ? "bg-primary text-primary-foreground rounded-3xl rounded-tr-sm px-3.5 py-2 text-sm"
                          : "bg-muted text-foreground rounded-3xl rounded-tl-sm px-3.5 py-2 text-sm"
                      }`}
                    >
                      <div>
                        <p className="whitespace-pre-wrap leading-6 text-sm">
                          {message.content}
                        </p>
                        {message.timestamp && isMounted && (
                          <p
                            className={`text-xs mt-2 opacity-60 ${
                              message.role === "user"
                                ? "text-primary-foreground/70"
                                : "text-muted-foreground"
                            }`}
                          >
                            {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </p>
                        )}
                      </div>

                      {/* Comparison Table - Show for comparison messages */}
                      {message.role === "assistant" && message.aiInsight && message.products && message.products.length >= 2 && (
                        <div className="mt-3 -mx-3.5">
                          <div className="px-3.5 overflow-x-auto">
                            <div className="min-w-[600px]">
                          <ComparisonTable aiInsight={message.aiInsight} products={message.products} />
                        </div>
                          </div>
                        </div>
                      )}

                      {/* Product Carousel - Show for regular product recommendations */}
                      {message.role === "assistant" && message.products && message.products.length > 0 && !message.aiInsight && (
                        <div className="mt-3 -mx-3.5">
                          <div className="px-3.5">
                          <ProductCarousel products={message.products} cardWidth={320} />
                            {message.products.length >= 2 && (
                              <div className="mt-3 flex justify-center">
                                <Button
                                  variant="outline"
                                  size="sm"
                                  onClick={() => handleCompareClick(message.products!.slice(0, 4).map(p => p.id))}
                                  className="text-xs"
                                  disabled={isLoading}
                                >
                                  <Scale className="h-3 w-3 mr-1.5" />
                                  Compare {message.products.length >= 4 ? '4' : message.products.length} Products
                                </Button>
                              </div>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Suggested Follow-ups - Show once after products or comparison */}
                      {message.role === "assistant" && message.suggestedFollowUps && message.suggestedFollowUps.length > 0 && (
                        <div className="mt-3 pt-2 border-t border-border/30">
                          <p className="text-xs font-medium text-muted-foreground mb-2">
                            Suggested follow-ups:
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {message.suggestedFollowUps.map((followUp, idx) => (
                              <Badge
                                key={idx}
                                variant="outline"
                                className="cursor-pointer hover:bg-primary hover:text-primary-foreground hover:border-primary transition-all text-xs py-1 px-2.5 rounded-full"
                                onClick={() => handleSuggestionClick(followUp)}
                              >
                                {followUp}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                    {message.role === "user" && (
                      <div className="shrink-0 w-7 h-7 rounded-full bg-primary flex items-center justify-center mt-0.5 text-primary-foreground text-xs font-medium">
                        U
                      </div>
                    )}
                  </div>
                </div>
              ))}

              {isLoading && (
                <div className="flex items-start gap-2.5 mb-5">
                  <div className="shrink-0 w-7 h-7 rounded-full bg-primary flex items-center justify-center mt-0.5">
                    <Sparkles className="h-3.5 w-3.5 text-primary-foreground" />
                  </div>
                  <div className="bg-muted text-foreground rounded-3xl rounded-tl-sm px-3.5 py-2 flex items-center gap-2">
                    <Loader2 className="h-3.5 w-3.5 animate-spin text-foreground" />
                    <span className="text-sm text-muted-foreground">
                      Thinking...
                    </span>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Suggestions */}
            {messages.filter((msg) => msg.role === "user").length === 0 && !isLoading && (
              <div className="border-t border-border/30 px-4 pt-3 pb-2 shrink-0 bg-background">
                <p className="text-xs font-medium text-muted-foreground mb-2.5 opacity-70">
                  Try asking:
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {SUGGESTIONS.map((suggestion, index) => (
                    <Badge
                      key={index}
                      variant="outline"
                      className="cursor-pointer hover:bg-primary hover:text-primary-foreground hover:border-primary transition-all text-xs py-1 px-2.5 rounded-full"
                      onClick={() => handleSuggestionClick(suggestion)}
                    >
                      {suggestion}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {/* Input Area */}
            <div className="border-t border-border/50 bg-background px-4 pt-3 pb-3 shrink-0">
              <div className="flex gap-2 items-end">
                <div className="flex-1 rounded-3xl border border-border bg-background px-3 py-2 focus-within:border-primary transition-all">
                  <input
                    ref={inputRef}
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyPress={handleKeyPress}
                    placeholder="Ask anything..."
                    className="w-full bg-transparent border-0 outline-none text-sm placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 touch-manipulation"
                    disabled={isLoading}
                    aria-label="Chat message input"
                  />
                </div>
                <Button
                  onClick={handleSend}
                  disabled={!input.trim() || isLoading}
                  size="icon"
                  className="shrink-0 h-9 w-9 rounded-full bg-primary text-primary-foreground hover:opacity-80 transition-all touch-manipulation disabled:opacity-50"
                >
                  {isLoading ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Send className="h-3.5 w-3.5" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );
}

