"use client";

import { useState, useRef, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ProductCarousel } from "@/components/features/products/product-carousel";
import { ComparisonTable } from "@/components/features/products/comparison-table";
import { sendChatMessage, type ChatMessage } from "@/lib/api/chat";
import type { Product } from "@/types/product";
import { Send, Loader2, Sparkles, Trash2, ArrowLeft, Home, Scale, ShoppingCart, History, Menu, X } from "lucide-react";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { toast } from "sonner";
import { ROUTES } from "@/lib/constants";
import { useComparison } from "@/contexts/comparison-context";
import { useCart } from "@/contexts/cart-context";
import { useOrders } from "@/contexts/order-context";

const SUGGESTIONS = [
  "Show me gym wear that works for meetings",
  "I need something for a formal event",
  "What are your best sellers?",
  "Show me casual everyday wear",
  "I'm looking for workout clothes",
  "What's trending right now?",
];

const STORAGE_KEY = "neusearch_chat_messages";

const getDefaultMessage = (): ChatMessage => ({
  role: "assistant",
  content: "Hello! I'm your product recommendation assistant. How can I help you find the perfect products today?",
  timestamp: new Date().toISOString(),
});

// Note: Follow-ups are now AI-generated by the backend based on user's previous message

// Load messages from localStorage
const loadMessagesFromStorage = (): ChatMessage[] => {
  if (typeof window === "undefined") return [];
  
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      // Validate it's an array
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch (error) {
    console.error("Error loading messages from localStorage:", error);
  }
  return [getDefaultMessage()];
};

// Save messages to localStorage
const saveMessagesToStorage = (messages: ChatMessage[]) => {
  if (typeof window === "undefined") return;
  
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages));
  } catch (error) {
    console.error("Error saving messages to localStorage:", error);
  }
};

export default function ChatPage() {
  const router = useRouter();
  const pathname = usePathname();
  const { products: comparisonProducts } = useComparison();
  const { getTotalItems } = useCart();
  const { getTotalOrders } = useOrders();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isMounted, setIsMounted] = useState(false);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messagesContainerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const lastMessageRef = useRef<HTMLDivElement>(null);
  
  const comparisonCount = comparisonProducts.length;
  const cartCount = getTotalItems();
  const orderCount = getTotalOrders();

  // Load messages from localStorage only on client side after mount
  useEffect(() => {
    setIsMounted(true);
    const loadedMessages = loadMessagesFromStorage();
    if (loadedMessages.length === 0) {
      setMessages([getDefaultMessage()]);
    } else {
      setMessages(loadedMessages);
    }
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollToShowMessage = () => {
    if (lastMessageRef.current && messagesContainerRef.current) {
      const container = messagesContainerRef.current;
      const messageElement = lastMessageRef.current;
      
      const containerRect = container.getBoundingClientRect();
      const messageRect = messageElement.getBoundingClientRect();
      
      // Check if message is already in view
      const isInView = 
        messageRect.top >= containerRect.top &&
        messageRect.bottom <= containerRect.bottom;
      
      if (!isInView) {
        // Scroll just enough to bring the message into view
        const scrollAmount = messageRect.top - containerRect.top + container.scrollTop - 100; // 100px padding from top
        container.scrollTo({
          top: scrollAmount,
          behavior: "smooth"
        });
      }
    }
  };

  // Save messages to localStorage whenever they change
  useEffect(() => {
    if (isMounted) {
      saveMessagesToStorage(messages);
    }
  }, [messages, isMounted]);

  // Scroll behavior: full scroll for user messages, minimal scroll for AI messages
  useEffect(() => {
    const lastMessage = messages[messages.length - 1];
    if (lastMessage) {
      if (lastMessage.role === "user") {
        scrollToBottom();
      } else if (lastMessage.role === "assistant") {
        // Small delay to ensure DOM is updated
        setTimeout(() => {
          scrollToShowMessage();
        }, 100);
      }
    }
  }, [messages]);

  // Close sidebar on desktop resize
  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth >= 1024) {
        setSidebarOpen(false);
      }
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: ChatMessage = {
      role: "user",
      content: input.trim(),
      timestamp: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);

    try {
      // Build conversation history
      const conversationHistory = messages
        .filter((msg) => msg.role !== "assistant" || !msg.products)
        .map((msg) => ({
          role: msg.role,
          content: msg.content,
        }));

      const response = await sendChatMessage({
        message: userMessage.content,
        conversation_history: conversationHistory,
        max_results: 5,
        similarity_threshold: 0.6,
      });

      const assistantMessage: ChatMessage = {
        role: "assistant",
        content: response.response,
        timestamp: new Date().toISOString(),
        products: response.products.length > 0 ? response.products : undefined,
        suggestedFollowUps: response.suggested_follow_ups && response.suggested_follow_ups.length > 0 
          ? response.suggested_follow_ups 
          : undefined,
      };

      setMessages((prev) => [...prev, assistantMessage]);
    } catch (error) {
      console.error("Error sending message:", error);
      
      // Show toast notification
      if (error instanceof Error) {
        if (error.message.includes("429")) {
          toast.error("Rate limit exceeded", {
            description: "Please wait a moment before sending another message.",
          });
        } else if (error.message.includes("NetworkError") || error.message.includes("Failed to fetch")) {
          toast.error("Network error", {
            description: "Please check your internet connection and try again.",
          });
        } else {
          toast.error("Failed to send message", {
            description: error.message || "Please try again later.",
          });
        }
      } else {
        toast.error("An unexpected error occurred", {
          description: "Please try again later.",
        });
      }
      
      const errorMessage: ChatMessage = {
        role: "assistant",
        content: "I'm sorry, I encountered an error. Please try again.",
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
      inputRef.current?.focus();
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInput(suggestion);
    inputRef.current?.focus();
  };

  const handleClearHistory = () => {
    if (confirm("Are you sure you want to clear the chat history?")) {
      const defaultMessages = [getDefaultMessage()];
      setMessages(defaultMessages);
      saveMessagesToStorage(defaultMessages);
      toast.success("Chat history cleared");
    }
  };

  return (
    <div className="h-screen bg-background text-foreground flex overflow-hidden">
      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside
        className={`fixed lg:static inset-y-0 left-0 z-50 lg:z-auto w-64 sm:w-72 border-r border-border bg-muted/30 flex flex-col shrink-0 transform transition-transform duration-300 ease-in-out ${
          sidebarOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0"
        }`}
      >
        {/* Sidebar Header */}
        <div className="px-3 sm:px-4 py-3 sm:py-4 border-b border-border shrink-0">
          <div className="flex items-center justify-between gap-2 sm:gap-3">
            <div className="flex items-center gap-2 sm:gap-3">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => {
                  router.back();
                  setSidebarOpen(false);
                }}
                className="h-8 w-8 sm:h-9 sm:w-9"
                aria-label="Go back"
              >
                <ArrowLeft className="h-4 w-4 sm:h-5 sm:w-5" />
              </Button>
              <div className="flex items-center gap-1.5 sm:gap-2">
                <Sparkles className="h-4 w-4 sm:h-5 sm:w-5" />
                <h2 className="text-base sm:text-lg md:text-xl font-semibold">AI Chat</h2>
              </div>
            </div>
            <ThemeToggle />
          </div>
        </div>

        {/* Navigation Links */}
        <nav className="flex-1 px-3 sm:px-4 py-3 sm:py-4 space-y-1 overflow-y-auto">
          <Link
            href={ROUTES.HOME}
            className={`flex items-center gap-2 sm:gap-3 px-2 sm:px-3 py-1.5 sm:py-2 rounded-lg text-xs sm:text-sm font-medium transition-colors ${
              pathname === ROUTES.HOME
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <Home className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span>Products</span>
          </Link>
          <Link
            href={ROUTES.CHAT}
            className={`flex items-center gap-2 sm:gap-3 px-2 sm:px-3 py-1.5 sm:py-2 rounded-lg text-xs sm:text-sm font-medium transition-colors ${
              pathname === ROUTES.CHAT
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <Sparkles className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span>Chat</span>
          </Link>
          <Link
            href={ROUTES.COMPARE}
            className={`flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-colors relative ${
              pathname === ROUTES.COMPARE
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <Scale className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span>Compare</span>
            {comparisonCount > 0 && (
              <Badge className="ml-auto h-5 w-5 p-0 flex items-center justify-center text-xs">
                {comparisonCount}
              </Badge>
            )}
          </Link>
          <Link
            href={ROUTES.CART}
            className={`flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-colors relative ${
              pathname === ROUTES.CART
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <ShoppingCart className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span>Cart</span>
            {cartCount > 0 && (
              <Badge className="ml-auto h-5 w-5 p-0 flex items-center justify-center text-xs">
                {cartCount}
              </Badge>
            )}
          </Link>
          <Link
            href={ROUTES.ORDER_HISTORY}
            className={`flex items-center gap-2 sm:gap-3 px-2 sm:px-3 py-1.5 sm:py-2 rounded-lg text-xs sm:text-sm font-medium transition-colors ${
              pathname === ROUTES.ORDER_HISTORY
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <History className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
            <span>Orders</span>
            {orderCount > 0 && (
              <Badge className="ml-auto">
                {orderCount}
              </Badge>
            )}
          </Link>
        </nav>

        {/* Clear History Button */}
        {messages.length > 1 && (
          <div className="px-3 sm:px-4 py-3 sm:py-4 border-t border-border shrink-0">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                handleClearHistory();
                setSidebarOpen(false);
              }}
              className="w-full flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm"
            >
              <Trash2 className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              <span>Clear History</span>
            </Button>
          </div>
        )}
      </aside>

      {/* Main Chat Area */}
      <main className="flex-1 flex flex-col overflow-hidden bg-background">
        {/* Mobile Header */}
        <div className="lg:hidden px-4 py-3 border-b border-border flex items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="h-9 w-9"
              aria-label="Toggle sidebar"
            >
              {sidebarOpen ? (
                <X className="h-5 w-5" />
              ) : (
                <Menu className="h-5 w-5" />
              )}
            </Button>
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5" />
              <h2 className="text-lg font-semibold">AI Chat</h2>
            </div>
          </div>
          <ThemeToggle />
        </div>

        {/* Messages Area */}
        <div 
          ref={messagesContainerRef}
          className="flex-1 overflow-y-auto px-3 sm:px-4 md:px-6 pt-4 sm:pt-6 md:pt-8 pb-4 sm:pb-6 md:pb-8 min-h-0"
        >
          {messages.map((message, index) => {
            const isLastMessage = index === messages.length - 1;
            return (
            <div 
              key={index} 
              ref={isLastMessage ? lastMessageRef : null}
              className="mb-4 sm:mb-6 md:mb-8 last:mb-0"
            >
              {/* Show both user and assistant messages */}
              <div className={`flex items-start gap-2 sm:gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>
                {message.role === "assistant" && (
                  <div className="shrink-0 w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-primary flex items-center justify-center mt-0.5">
                    <Sparkles className="h-3.5 w-3.5 sm:h-4 sm:w-4 text-primary-foreground" />
                  </div>
                )}
                <div
                  className={`flex-1 max-w-[90%] xs:max-w-[85%] sm:max-w-[75%] md:max-w-[70%] ${
                    message.role === "user"
                      ? "bg-muted rounded-3xl rounded-tr-sm px-3 py-2 sm:px-4 sm:py-2.5 md:px-5 md:py-3 text-sm sm:text-base text-foreground"
                      : "bg-muted rounded-3xl rounded-tl-sm px-3 py-2 sm:px-4 sm:py-2.5 md:px-5 md:py-3 text-sm sm:text-base text-foreground"
                  }`}
                >
                  {/* Message Text */}
                  <div>
                    <p className="whitespace-pre-wrap leading-6 sm:leading-7 text-sm sm:text-[15px] md:text-base text-foreground">
                      {message.content}
                    </p>
                    {message.timestamp && isMounted && (
                      <p className="text-[10px] xs:text-xs mt-1.5 sm:mt-2.5 opacity-60 text-muted-foreground">
                        {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </p>
                    )}
                  </div>

                  {/* Comparison Table - Show for comparison messages */}
                  {message.role === "assistant" && message.aiInsight && message.products && message.products.length >= 2 && (
                    <div className="mt-3 sm:mt-4">
                      <ComparisonTable aiInsight={message.aiInsight} products={message.products} />
                    </div>
                  )}

                  {/* Suggested Follow-ups - Show after comparison messages */}
                  {message.role === "assistant" && message.aiInsight && message.suggestedFollowUps && message.suggestedFollowUps.length > 0 && (
                    <div className="mt-3 sm:mt-4 pt-2 sm:pt-3 border-t border-border">
                      <p className="text-[10px] xs:text-xs font-medium text-muted-foreground mb-2 sm:mb-2.5">
                        Suggested follow-ups:
                      </p>
                      <div className="flex flex-wrap gap-1.5 sm:gap-2">
                        {message.suggestedFollowUps.map((followUp, idx) => (
                          <Badge
                            key={idx}
                            variant="outline"
                            className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-all text-[10px] xs:text-xs py-1 xs:py-1.5 px-2 xs:px-3 rounded-full touch-manipulation"
                            onClick={() => {
                              handleSuggestionClick(followUp);
                              setSidebarOpen(false);
                            }}
                          >
                            {followUp}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Product Carousel - Show for regular product recommendations */}
                  {message.role === "assistant" && message.products && message.products.length > 0 && !message.aiInsight && (
                    <div className="mt-3 sm:mt-4 -mx-3 sm:-mx-4 md:-mx-5">
                      <div className="px-3 sm:px-4 md:px-5 py-3 sm:py-4 bg-card/50 dark:bg-card/30 rounded-lg border border-border/50">
                        <ProductCarousel products={message.products} cardWidth={260} />
                      </div>
                    </div>
                  )}

                  {/* Suggested Follow-ups - Show after regular product recommendations */}
                  {message.role === "assistant" && message.suggestedFollowUps && message.suggestedFollowUps.length > 0 && !message.aiInsight && (
                    <div className="mt-3 sm:mt-4 pt-2 sm:pt-3 border-t border-border">
                      <p className="text-[10px] xs:text-xs font-medium text-muted-foreground mb-2 sm:mb-2.5">
                        Suggested follow-ups:
                      </p>
                      <div className="flex flex-wrap gap-1.5 sm:gap-2">
                        {message.suggestedFollowUps.map((followUp, idx) => (
                          <Badge
                            key={idx}
                            variant="outline"
                            className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-all text-[10px] xs:text-xs py-1 xs:py-1.5 px-2 xs:px-3 rounded-full touch-manipulation"
                            onClick={() => {
                              handleSuggestionClick(followUp);
                              setSidebarOpen(false);
                            }}
                          >
                            {followUp}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
                {message.role === "user" && (
                  <div className="shrink-0 w-8 h-8 rounded-full bg-primary flex items-center justify-center mt-0.5">
                    <span className="text-xs font-medium text-primary-foreground">U</span>
                  </div>
                )}
              </div>
            </div>
            );
          })}

          {isLoading && (
            <div className="flex items-start gap-2 sm:gap-3 mb-4 sm:mb-6 md:mb-8">
              <div className="shrink-0 w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-primary flex items-center justify-center mt-0.5">
                <Sparkles className="h-3.5 w-3.5 sm:h-4 sm:w-4 text-primary-foreground" />
              </div>
              <div className="bg-muted rounded-3xl rounded-tl-sm px-3 py-2 sm:px-4 sm:py-2.5 flex items-center gap-2 sm:gap-2.5">
                <Loader2 className="h-3.5 w-3.5 sm:h-4 sm:w-4 animate-spin text-primary" />
                <span className="text-xs sm:text-sm text-muted-foreground">
                  Thinking...
                </span>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Suggestions */}
        {messages.filter((msg) => msg.role === "user").length === 0 && !isLoading && (
          <div className="border-t border-border px-4 sm:px-6 pt-4 pb-3 shrink-0">
            <p className="text-xs font-medium text-muted-foreground mb-3">
              Try asking:
            </p>
            <div className="flex flex-wrap gap-2">
              {SUGGESTIONS.map((suggestion, index) => (
                <Badge
                  key={index}
                  variant="outline"
                  className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-all text-xs py-1.5 px-3 rounded-full touch-manipulation"
                  onClick={() => handleSuggestionClick(suggestion)}
                >
                  {suggestion}
                </Badge>
              ))}
            </div>
          </div>
        )}

        {/* Input Area */}
        <div className="border-t border-border bg-background px-3 sm:px-4 md:px-6 pt-3 sm:pt-4 pb-3 sm:pb-4 md:pb-6 shrink-0">
          <div className="flex gap-2 sm:gap-3 items-end">
            <div className="flex-1 rounded-3xl border border-input bg-background px-3 py-2 sm:px-4 sm:py-2.5 md:py-3 focus-within:border-primary focus-within:ring-1 focus-within:ring-primary transition-all">
              <input
                ref={inputRef}
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Ask anything..."
                className="w-full bg-transparent border-0 outline-none text-sm sm:text-base placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 touch-manipulation"
                disabled={isLoading}
                aria-label="Chat message input"
                aria-describedby="chat-input-help"
              />
            </div>
            <Button
              onClick={handleSend}
              disabled={!input.trim() || isLoading}
              size="icon"
              className="shrink-0 h-9 w-9 sm:h-10 sm:w-10 md:h-11 md:w-11 rounded-full"
            >
              {isLoading ? (
                <Loader2 className="h-3.5 w-3.5 sm:h-4 sm:w-4 animate-spin" />
              ) : (
                <Send className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              )}
            </Button>
          </div>
          <p id="chat-input-help" className="text-[10px] xs:text-xs text-muted-foreground mt-1.5 sm:mt-2 text-center hidden sm:block">
            Press Enter to send, Shift+Enter for new line
          </p>
        </div>
      </main>
    </div>
  );
}
